#!/usr/bin/env python3
# tools/bundle_cli.py
"""Bundle the stdlib-only AcerControl CLI into dist/acercontrol (CLI-07).

Approach: concatenate the relevant acercontrol/*.py files (after
stripping cross-imports between them) with a single __main__ shim
at the end. The bundled file is a stdlib-only Python script with
no package imports — works as `cp dist/acercontrol /usr/local/bin/`.

Why not zipapp / shiv / PyInstaller:
- zipapp works (stdlib), but produces a zip-prefixed file — debugging
  is harder, error tracebacks reference the zip member path.
- shiv / PyInstaller / Nuitka all add build-time deps; PROJECT.md
  forbids pip-only packages for the GUI but Phase 2 chooses to extend
  the zero-deps invariant to build-time too (one less moving piece).
- This concat approach is ~140 LOC and produces a debuggable file.

ISSUE-01 fix: every Phase 1 + Phase 2 source begins with
`from __future__ import annotations`. PEP 236 mandates that
`from __future__` imports MUST be the first statement after the
optional module docstring. If we naively concatenate the sources,
every source after the first would have an illegal late
`from __future__` import → SyntaxError. We hoist the directive into
the HEADER (single canonical line) and use `_strip_future_imports`
to comment out per-source occurrences (preserves source line numbers
for stack-trace readability, parallel to `_strip_intra_imports`).

Inputs and outputs are GTK-free. verify_no_gtk.py guards this at
both pre-bundle (each input source) and post-bundle (dist/acercontrol).
"""
from __future__ import annotations
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Order matters — definitions must precede uses.
BUNDLE_ORDER = [
    REPO / "acercontrol" / "profiles.py",
    REPO / "acercontrol" / "sysfs.py",
    REPO / "acercontrol" / "core.py",
    REPO / "acercontrol" / "features.py",
    REPO / "acercontrol" / "privilege.py",
    REPO / "acercontrol" / "cli.py",
]

OUTPUT = REPO / "dist" / "acercontrol"

# HEADER is the single canonical source of `from __future__ import annotations`
# in the bundled output. PEP 236 requires `from __future__` to be the first
# statement after any module docstring — we hoist it here and strip per-source
# occurrences via `_strip_future_imports` (ISSUE-01 fix vs research pattern).
HEADER = '''#!/usr/bin/env python3
"""acercontrol — bundled single-file CLI (CLI-07).

Generated by tools/bundle_cli.py. Do not edit this file directly.
Source: https://github.com/acercontrol/acercontrol
"""
from __future__ import annotations
'''

# SELF_ALIASES bridges qualified module references that survive after
# intra-imports are commented (Rule 1 fix vs research pattern; P2-NEW-08).
# `features.py` does `from acercontrol import core` then uses
# `core.PREDATOR_V4_PARAM`; `core.py` does `from acercontrol import sysfs as
# _sysfs` then uses `_sysfs.X`. Binding these names to the bundle's own
# module object preserves qualified access in the concatenated output.
SELF_ALIASES = '''
# Bundle self-aliases — bind qualified module names to the bundle's own
# namespace so cross-module references like `core.X` and `_sysfs.Y` resolve.
# Symbol aliases (`_current_profile_ui`, `_available_profiles`) bridge
# stripped `as` imports inside `core.py`. Lazy-bound at first cmd run via
# globals().setdefault to avoid NameError when concat order surfaces them
# before the original symbol is defined.
import sys as _bundle_sys
_bundle_self = _bundle_sys.modules[__name__]
core = _bundle_self
sysfs = _bundle_self
_sysfs = _bundle_self
features = _bundle_self
profiles = _bundle_self
privilege = _bundle_self
'''

# Per-source alias bindings injected after profiles.py concatenation
# (because they reference symbols defined IN profiles.py — must come after).
POST_PROFILES_ALIASES = '''
# Aliases for `as _name` imports inside core.py (originally:
# `from acercontrol.profiles import (current_profile_ui as _current_profile_ui,
#  available_profiles as _available_profiles)`).
_current_profile_ui = current_profile_ui
_available_profiles = available_profiles
'''

# Regex matches `from acercontrol[...] import X` and `import acercontrol[...]`
# at the start of a line. These imports are intra-bundle and must be stripped.
# Two forms covered:
#   A. Single-line:    from acercontrol[.X] import ...   |   import acercontrol[.X][ as N]
#   B. Parenthesised:  from acercontrol[.X] import (\n  ... \n)
# The parenthesised form (cli.py + core.py both use it) requires DOTALL to
# span newlines; without explicit handling the regex would only comment the
# first line and leave a dangling `Profile,\n  PROFILES,\n  ...)` block →
# IndentationError. Rule 1 fix vs research pattern.
_INTRA_IMPORT = re.compile(
    r"^(from\s+acercontrol(\.\w+)?\s+import\s+\([^)]*\)|"          # parenthesised (multi-line)
    r"from\s+acercontrol(\.\w+)?\s+import\s+.+|"                    # single-line from
    r"import\s+acercontrol(\.\w+)?\s*(as\s+\w+)?)",                 # single-line import
    re.MULTILINE,
)

# Regex matches the canonical single-line form
# `from __future__ import annotations`. Every Phase 1 and Phase 2 source
# starts with this line; we strip per-source occurrences and rely on the
# hoisted HEADER directive for the bundle.
_FUTURE_IMPORT = re.compile(
    r"^from\s+__future__\s+import\s+annotations\s*$",
    re.MULTILINE,
)

# Regex matches `if __name__ == "__main__":` blocks — features.py's
# `_print_report(probe())` block would fire BEFORE the bundler's appended
# `sys.exit(main())` shim, never reaching the CLI entry. We comment out
# every per-source main block; the bundler appends a single canonical one
# at the end (Rule 1 fix vs research pattern; P2-NEW-08).
_MAIN_BLOCK = re.compile(
    r"^if\s+__name__\s*==\s*['\"]__main__['\"]\s*:\s*\n(?:[ \t]+.*\n?)+",
    re.MULTILINE,
)


def _strip_intra_imports(src: str) -> str:
    """Comment out imports that resolve inside the bundle.

    We comment rather than delete so line numbers in stack traces
    still map back to the source file. For parenthesised multi-line
    imports we prepend `# bundled: ` to every line of the match so all
    lines become comments (not just the first — that would leave a
    dangling `Profile,\n  PROFILES,\n)` block → IndentationError).
    """
    def _comment_all_lines(m):
        return "\n".join("# bundled: " + line for line in m.group(0).splitlines())
    return _INTRA_IMPORT.sub(_comment_all_lines, src)


def _strip_future_imports(src: str) -> str:
    """Comment out per-source `from __future__ import annotations` lines.

    The HEADER carries the single hoisted directive for the whole bundle.
    We comment (not delete) to preserve source line numbers for
    stack-trace readability — same idiom as `_strip_intra_imports`.
    """
    return _FUTURE_IMPORT.sub(lambda m: "# bundled: " + m.group(0), src)


def _strip_main_blocks(src: str) -> str:
    """Comment out per-source `if __name__ == "__main__":` blocks.

    The bundler appends a single canonical `sys.exit(main())` shim at the
    end. Per-source main blocks (e.g. `features.py`'s `_print_report(probe())`)
    would fire FIRST when the bundle is run as `__main__` and short-circuit
    the CLI entry. Comment-prefix every line of each match (parallel to
    `_strip_intra_imports`).
    """
    def _comment_all_lines(m):
        return "\n".join("# bundled: " + line for line in m.group(0).splitlines())
    return _MAIN_BLOCK.sub(_comment_all_lines, src)


def _check_no_gtk(src: str, source_path: Path) -> None:
    """Inline guard — refuses to bundle GTK imports (CLI-07).

    Pre-bundle stage. verify_no_gtk.py does a separate post-bundle check
    on dist/acercontrol (P2-NEW-06 belt-and-braces).
    """
    if re.search(r"^(import\s+gi|from\s+gi(\.|\s))", src, re.MULTILINE):
        raise SystemExit(
            f"refusing to bundle {source_path}: contains `import gi` "
            f"or `from gi` — CLI-07 violation"
        )


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    out_lines: list = [HEADER, SELF_ALIASES, ""]
    for src in BUNDLE_ORDER:
        if not src.exists():
            raise SystemExit(f"missing source: {src}")
        text = src.read_text(encoding="utf-8")
        _check_no_gtk(text, src)
        text = _strip_intra_imports(text)
        text = _strip_future_imports(text)
        text = _strip_main_blocks(text)
        out_lines.append(f"# === BEGIN {src.name} ===")
        out_lines.append(text)
        out_lines.append(f"# === END {src.name} ===")
        # Inject per-source alias bindings AFTER the source they depend on.
        if src.name == "profiles.py":
            out_lines.append(POST_PROFILES_ALIASES)
        out_lines.append("")

    # __main__ shim — main() is defined by cli.py at the bottom of the bundle.
    out_lines.append("if __name__ == '__main__':")
    out_lines.append("    import sys")
    out_lines.append("    sys.exit(main())")

    OUTPUT.write_text("\n".join(out_lines), encoding="utf-8")
    OUTPUT.chmod(0o755)
    print(f"wrote {OUTPUT}  ({OUTPUT.stat().st_size} bytes)")

    # Post-bundle verification — run verify_no_gtk.py on the OUTPUT
    # (P2-NEW-06 belt-and-braces).
    verifier = REPO / "tools" / "verify_no_gtk.py"
    rc = subprocess.run([sys.executable, str(verifier), str(OUTPUT)]).returncode
    if rc != 0:
        OUTPUT.unlink(missing_ok=True)
        raise SystemExit(f"verify_no_gtk.py failed on {OUTPUT}; bundle removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
